# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: assets/generate-pages

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Docker Layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      # Runs a single command using the runners shell
      - name: Build the static site
        run: docker-compose run --rm --entrypoint "/bin/bash -c 'npm install;npx eleventy'" eleventy

      - name: Test the generated pages
        run: |
          mkdir -p smashtest
          chmod -R a+rw smashtest
          docker-compose -f docker-compose.tests.yml run --rm smashtest

      - name: Upload Smashtest Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: smashtest-report
          path: assets/generate-pages/smashtest/ 
          
        
